// Code generated by mockery. DO NOT EDIT.

package borrow

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockBorrowController is an autogenerated mock type for the BorrowController type
type MockBorrowController struct {
	mock.Mock
}

// CreateBorrow provides a mock function with given fields: c
func (_m *MockBorrowController) CreateBorrow(c *gin.Context) {
	_m.Called(c)
}

// IsBookBorrowed provides a mock function with given fields: c
func (_m *MockBorrowController) IsBookBorrowed(c *gin.Context) {
	_m.Called(c)
}

// NewMockBorrowController creates a new instance of MockBorrowController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBorrowController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBorrowController {
	mock := &MockBorrowController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
