version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    depends_on:
      - db